### ISSUE TITLE
Best way to specify a non-standard cache directory

### ISSUE THREAD

**Issue by QuintinPope** [kmeng01/rome#13]
Hello,

Due to memory limitations, I need to store ROME's cache somewhere other than my home directory. What would be the best way to specify the new cache dir's location so that all of ROME's components know where to find the data they need?

Also, I intend to run ROME on custom trained GPT-2 models, so the cache dir also needs to hold the data used to calculate covariance statistics for those models. 

Thanks for your help, and thanks so much for providing this repository!

**Comment by kmeng01** [comment]
Hi @QuintinPope! We specify the directories in the [.env file](https://github.com/kmeng01/rome/blob/main/.env). Can you try modifying the `RESULTS_DIR` and `STATS_DIR` to change where the results cache and covariance statistics are stored, respectively?

Let me know if this doesn't work!
