### ISSUE TITLE
T5 support

### ISSUE THREAD

**Issue by puraminy** [kmeng01/rome#2]
Hi, thanks for great job
I wonder if you plan to support T5 model? if not do you think changing the code for T5 is easy or not?

**Comment by kmeng01** [comment]
Hi, thanks for the question! If I recall correctly, T5 has an encoder-decoder architecture in which the autoregressive decoder can cross attend to hidden representations from the encoder. While I think an extension to enc-dec is possible, our paper does not provide a principled method for doing so. This is a promising area for future work, but it's unfortunately currently out of scope.

**Comment by puraminy** [comment]
Thank you
