### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)

### ISSUE THREAD

**Issue by JayThibs** [kmeng01/rome#23]
I tried running the model editing notebook in Colab, but ran into the following issue:

`ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)`

This is because `Literal` is only available in Python 3.8+ while Colab supports 3.7. Was this a recent change?

I can spin up my own python 3.8 instance or add some additional code to install Python 3.8 in Colab, but that won't solve the issue for others unless I add the conda python 3.8 installation in a PR. Will this be fixed?

**Comment by kmeng01** [comment]
Ah, yes, this was a recent change! Thanks for catching the error, will revert so that things remain backward-compatible with Colab.

**Comment by kmeng01** [comment]
Fixed the issue, thanks for your patience. Let me know if there's anything else you need!
