### ISSUE TITLE
Documentation for hparams?

### ISSUE THREAD

**Issue by moyix** [kmeng01/rome#27]
Is there any documentation on what the [various hparams here](https://github.com/kmeng01/rome/blob/main/hparams/ROME/EleutherAI_gpt-j-6B.json) mean? I'm trying to use ROME with a different GPT-J 6B model ([CodeGen-6B-mono](https://huggingface.co/moyix/codegen-6B-mono-gptj)) using the demo `rome.ipynb` notebook. The comments you had in [this issue](https://github.com/kmeng01/rome/issues/25) were helpful but I don't really know the meanings of:

* `layers`: it seems like this says which layers to modify. But this isn't known in advance, and has to be found using the techniques described in the paper, right? So maybe I need to dig through the repo to find the code that does that?
* Any of the `mom2_*` parameters. Given that they reference `wikitext` maybe I need to provide a code dataset instead? I couldn't find any reference to `mom` in the paper.

The others I *think* I can figure out from the paper and do some hyperparameter sweeps, but I don't really know where to start with the ones above.

(Thanks very much for releasing the code BTW! I'm really excited to try it out on code models :) )

**Comment by moyix** [comment]
Ok, I think I understand `layers` – running the `causal_trace.ipynb` and looking at those figures suggests some candidate MLP layers that I can then provide as hparams. The `mom2` ones seem to be described briefly in section E.2 of the paper, and it looks like I will have to use a code dataset for these. I think I can figure it out from here, thanks :)

**Comment by kmeng01** [comment]
Hi @moyix! Your interpretations are correct, thanks for clarifying them -

Let us know how things go on the code task! We've never tried something like that before, so there might be some hiccups along the way + interesting new research questions. Happy to chat about them at some point, if you'd like :)
